const ActionTypes = {
    USERNAME_UPDATED: "USERNAME_UPDATED",
    CONNECTED_PLAYERS_UPDATED: "CONNECTED_PLAYERS_UPDATED",
    PLAYER_STATE_UPDATED: "PLAYER_STATE_UPDATED",
    RESET_STATE: "RESET_STATE"
}

export default ActionTypes